### PR TITLE
hotfix wrong regex

### PR DESCRIPTION
**Pull request by jrweb247**

### CODE REVIEW

**Comment by jonathantneal** [comment]
Please provide more information. Why are you changing this?

The current RegExp does not require a fallback to be specified and you have changed that.

**Comment by jonathantneal** [comment]
I also see the tests are failing. We can reopen this if you provide some information.

**Comment by jrweb247** [comment]
https://regex101.com/r/sPI23e/2 doesn't work anymore 

with de PR : 

https://regex101.com/r/sPI23e/3

**Comment by jonathantneal** [comment]
@jrweb247, the RegExp is not capturing the whole declaration, property, and value.

See: https://github.com/postcss/postcss-custom-properties/blob/master/index.js#L7

And note the comment (that has not been changed in 6.3.0):

```
// matches `name[, fallback]`, captures "name" and "fallback"
```

This matcher is used on [L50](https://github.com/postcss/postcss-custom-properties/blob/master/index.js#L50) on `matches.body`, which is everything within the parentheses of the `var()`.

Better text to test would be `grey` and `grey, fallback`.

**Comment by jrweb247** [comment]
sorry it's difficult to write in english but your last release 6.3.0 break our production deployement, I think it's because the regex, because before and after the regex doesn't match same things see: 

https://regex101.com/r/aNEo6B/1

**Comment by jonathantneal** [comment]
@jrweb247, have you tried 6.3.1?

**Comment by jrweb247** [comment]
sorry 6.3.0 was removed ? can't see 6.3.1 :-(

**Comment by jonathantneal** [comment]
https://www.npmjs.com/package/postcss-custom-properties

**Pull request closed without merging**
