### PR TITLE
Use the new PostCSS 8.0 API

### LINKED ISSUE #230: Doesn't convert variable with postcss mixin
Hello!
In new versions:
`postcss-custom-properties 10.0.0` and `postcss-mixins 7.0.`

I have mixin like below: 

```
@define-mixin font $weight, $minFont, $maxFont, $minLine, $maxLine, $family {
  font-size: responsive $minFont $maxFont;
  font-range: var(--min-max);
  font-weight: $weight;
  font-family: $family;
  line-height: responsive $minLine $maxLine;
  line-height-range: var(--min-max);
}
```

and var like:

```
:root {
  --font: 'Arial', helvetica, sans-serif;
  --min-max: 320px 2560px;
}
```

in css file - use 

```
@mixin font normal, 14px, 24px, 20px, 24px, var(--font);
```

output:

```
  font-size: responsive 14px 24px;
  font-range: 320px 2560px;
  font-weight: normal;
  font-family: var(--font); <------ Not Converted
  line-height: responsive 20px 24px;
  line-height-range: 320px 2560px;
```

### PR DESCRIPTION
**Pull request by SergeAstapov**
This follows https://evilmartians.com/chronicles/postcss-8-plugin-migration and suggestion from @ai in https://github.com/postcss/postcss-nested/issues/124#issuecomment-827611219

Potentially resolves #230.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
Hi @jonathantneal @Semigradsky @ai, sorry to bother. Would you be able to advice if something may need to be tweaked in this PR or if it's good to be merged and released?

Had exact same issue as outlined in #230, was using this branch for few weeks and didn't notice any issues since then.

**Comment by ai** [comment]
I contacted @Semigradsky by email. If he will not respond in a week, feel free to ping me again, I will merge and release it.

**Comment by adamjkb** [comment]
@ai 👋 Would it be possible to create a release containing these changes so that #230 will be truly resolved.

Thank you!

**Comment by ai** [comment]
Hm. I do not have npm access.

**Comment by jonathantneal** [comment]
It is published, @adamjkb, @SergeAstapov, @ai!

Change log: https://github.com/postcss/postcss-custom-properties/releases/tag/v12.0.0

**Pull request merged**
