### PR TITLE
feat: update to postcss ^7.0.2

### PR DESCRIPTION
**Pull request by douglasduteil**
Hi @postcss

Here comes another little update :)

### CODE REVIEW

**Comment by douglasduteil** [comment]
You might want to merge #126 first :wink:

**Comment by jonathantneal** [comment]
Thanks, @douglasduteil !

**Comment by douglasduteil** [comment]
You are welcome @jonathantneal 
When will you publish it on npm ?

**Comment by jonathantneal** [comment]
There are major changes needed to this plugin, so I’d another two weeks to potentially get those in.

**Pull request merged**
