### PR TITLE
feat: upgrade postcss-values-parser to version without high risk vulnererability

### PR DESCRIPTION
**Pull request by davilima6**
See
- https://www.npmjs.com/advisories/1550
- https://github.com/shellscape/postcss-values-parser/issues/120

### CODE REVIEW

**Comment by davilima6** [comment]
Tests fail for Node 8:

```
$ npm test
> postcss-custom-properties@9.1.1 test /home/travis/build/postcss/postcss-custom-properties
> npm run test:js && npm run test:tape
> postcss-custom-properties@9.1.1 test:js /home/travis/build/postcss/postcss-custom-properties
> eslint src/{*,**/*}.js --cache --ignore-path .gitignore --quiet
> postcss-custom-properties@9.1.1 pretest:tape /home/travis/build/postcss/postcss-custom-properties
> rollup -c .rollup.js --silent
> postcss-custom-properties@9.1.1 test:tape /home/travis/build/postcss/postcss-custom-properties
> postcss-tape
/home/travis/build/postcss/postcss-custom-properties/node_modules/is-url-superb/index.js:11
	} catch {
	        ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/postcss/postcss-custom-properties/node_modules/postcss-values-parser/lib/nodes/Word.js:12:15)
npm ERR! code ELIFECYCLE
```

Would you mind if we added `package-lock.json` ?

**Comment by Semigradsky** [comment]
@davilima6 [postcss-values-parser 4.x](https://github.com/shellscape/postcss-values-parser/releases/tag/v4.0.0) has breaking changes: `Node v10+ now required`

**Comment by davilima6** [comment]
Would you mind dropping support for Node 8?

**Comment by Semigradsky** [comment]
We will do it in next major version with Postcss 8 support

**Comment by davilima6** [comment]
I see, so what is your suggestion for this PR/fix? Should it wait for such next major?

**Comment by Semigradsky** [comment]
Hm, I will publish new major version. Why not

**Comment by Semigradsky** [comment]
https://github.com/postcss/postcss-custom-properties/releases/tag/10.0.0

**Pull request merged**
