### PR TITLE
Add an option to disable the undefined and no fallback variable

### PR DESCRIPTION
**Pull request by Spy-Seth**
I need to be able to pre-compile the style of a library of component. But I could not resolve yet all the variable (some customization related variable: colors, font-family...). My user (me in another application) will have to finish the compilations.

So on this pre-compilation time I want to remove the warnings. And later on the final compilation I will let the warning active.

### CODE REVIEW

**Comment by MoOx** [comment]
Can you provide some explanation about the motivation for this?

**Comment by Spy-Seth** [comment]
Ho! Sorry I forgot this step 😄 

Description filled!

**Comment by MoOx** [comment]
Why don't you instead make a plugin after this one that remove the message? I don't think it's a good idea to add this option as it allows people to just ignored warnings too easily. Since your case is specific, I guess you could just write a plugin that will take your 3 or 4 lines of code to remove the messages from postcss messages registry?

**Comment by Spy-Seth** [comment]
> I guess you could just write a plugin that will take your 3 or 4 lines of code to remove the messages from postcss messages registry?

I doesn't know that is possible! I will give it a try.

**Comment by Spy-Seth** [comment]
Ok. I succeed doing it with a plugin: https://gist.github.com/Spy-Seth/0d8c88f7eb81edb4842f493b7e28a8cc

You right, it's an edge case that should not me managed by this library.

**Pull request closed without merging**
