### PR TITLE
Let "warnings" option silence all warnings

### PR DESCRIPTION
**Pull request by bundyo**
The main reason for this change is that I'm building an Electron app and I don't need fallbacks for my variables. 

P.S. If the warnings themselves are not a reason enough, please also consider build logs getting huge and hard to find something in them.

### CODE REVIEW

**Comment by MoOx** [comment]
So you use code that's not going to work? Electron is supporting custom props already since it's chrome http://caniuse.com/#search=custom%20proper
So why do you use this plugin in the first place?

**Comment by bundyo** [comment]
Yes, Electron (Chrome) supports custom properties, but it doesn't support the [color function](https://github.com/postcss/postcss-color-function), so in order for postcss to compile it, I need to also use postcss-custom-properties (with preserve: "computed"), even if I don't really need it in the renderer. I wonder if postcss can make use of libchromiumcontent to avoid such issues... probably not, but that's not the point of this pull request. :)

**Comment by bundyo** [comment]
Do we have a decision regarding this issue?

**Comment by s-panferov** [comment]
Plz merge this. This is useful when you're using both "real" and "fake" custom properties.

**Comment by jonathantneal** [comment]
I use real and fake custom properties, too. This would be very helpful.

**Comment by jonathantneal** [comment]
@MoOx, no one is assigned to this. May I assign myself, resolve the conflicts, and merge? There is a need for this, particularly when one _must_ rely on real custom properties.

Here’s my case:

```css
.some-slideout-drawer {
  min-height: 100vh;
  min-height: var(--inner-vh, 100vh);
  width: calc(100vw - 50px);
  width: calc(var(--inner-vw, 100vw) - 50px);
}
```

Where `--inner-vw` and `--inner-vh` are defined as:

```js
function onresize() {
  document.documentElement.style.setProperty('--inner-vw', `${document.documentElement.clientWidth}px`);
  document.documentElement.style.setProperty('--inner-vh', `${document.documentElement.clientHeight}px`);
}
```

I need this to get around the false `vw` and `vh` units in newer iOS Safari and Edge.

**Comment by bundyo** [comment]
I've updated to latest.

**Comment by s-panferov** [comment]
Our company is really suffering from this. What kind of help can we provide to help with this merge?

**Comment by jonathantneal** [comment]
@s-panferov, I feel your pain. I’m the only person available to look at this right now, and I would like this as well. @ai, do I have the permissions to review, merge, and cut a new release?

Related; I think we need more collaborators, at least for these individual projects.

**Comment by ai** [comment]
@jonathantneal I have no permission to publish.

Why do you need so many reviews? :) This PR is simple. Release it :)

**Comment by jonathantneal** [comment]
Tests have [passed](https://travis-ci.org/postcss/postcss-custom-properties).

Published as a minor update — 6.1.0 — as this adds functionality in a backwards-compatible manner.

**Pull request merged**
