### PR TITLE
8.0.0

### LINKED ISSUE #80: Generating one separate stylesheet per theme
Right now we are using a scss mixin ( https://github.com/zellwk/themify ) to provide different themes for our react components in our app.

It works great, but produces rather long selector chains in the compiled css file.

While we do have to provide the ability to change themes during runtime ( which is no hassle with the current solution, we only have to switch one classname on the body element ) the default usecase is, that the theme does not change. 

So we thought about reducing the complexity and filesize of our stylesheets by splitting them up in separate files. 

Example: 

**themes.scss:**

    $themes: (
      red: (
        mainColor: #aa3939,
        secondaryColor: #D46A6A
      ),
      blue: (
        mainColor: #2e4272,
        secondaryColor: #4f628e
      )
    );

**button.sccs**

    @import 'themes.scss';
    
    .button {
      @include themify($themes) {
        color: themed('secondaryColor');  
        background-color: themed('mainColor');  
      }}
    }

This becomes:

    .theme-red .button {
      color: #D46A6A;
      background-color: #aa3939;
    }
    
    .theme-blue .button {
      color: #4f628e;
      background-color: #2e4272;
    }

Now I want this to become:

**theme-red.css:**

    .button {
      color: #D46A6A;
      background-color: #aa3939;
    }

**theme-blue.css:**

    .button {
      color: #4f628e;
      background-color: #2e4272;
    }

How would I achieve this with postcss and custom properties?

Thanks a lot!

### LINKED ISSUE #100: support html selector in addition to :root
We're currently running up against a bug with latest MS Edge in that when printing, variables declared in `:root` are no properly handled (bot the variables and fallbacks are ignored. See: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16025710/). Using `html`, however, does work. Since `:root` and `html` are more-or-less synonymous, would it possible for this plugin to also support variable declarations in `html`?

### LINKED ISSUE #102: AppendVariables results in thousands of duplicate entries
I'm using Webpack with postcss loader and extract text plugin. This results in postcss-custom-properties plugin to be called multiple times, for each imported css file.

So when appendVariables is set to true the appended ":root" section is duplicated multiple times in the resulted css. This slows down chrome dev tools and significally increases css file size.

### LINKED ISSUE #109: Duplication declaration with `preserve: true` and `strict: false`
Hello. Plugin add always duplicate declarations with options `preserve: true` and `strict: false`. Example:

```
         require('postcss-cssnext')({
            browsers: [
              'last 2 version'
            ],
            features: {
              rem: false,
              customProperties: {
                strict: false,
                warnings: false,
                preserve: true
              }
            }
          }),
```

Input:

```
.form-field__input
  width: 99%
  font-size: 1.8rem
  color: var(--emphColor)
  border-radius: 6px
  border: 1px solid var(--commentColor)
  background-color: color(var(--headsColor) tint(4%))
```

Output:

```
.form-field__input {
  width: 99%;
  font-size: 1.8rem;
  color: var(--emphColor);
  color: var(--emphColor);
  border-radius: 6px;
  border: 1px solid var(--commentColor);
  border: 1px solid var(--commentColor);
  background-color: color(var(--headsColor) tint(4%));
  background-color: color(var(--headsColor) tint(4%)); }
```

Looks like it still trying to add fallback. Is it possible to disable such behaviour of plugin?

postcss-custom-properties version 6.2.0

### LINKED ISSUE #113: PostCSS log var(--property) warnings not triggered by postcss when the variable references an undeclared variable
This [issue references the previous issue I filed with the same title](https://github.com/postcss/postcss-custom-properties/issues/112), BUT I will provide a much simpler explanation.  If you have some CSS variables declared like this:

```css
:root {
    --color-gray-light: blue;
}
  
:root {
    --color-abbr-border:             var(--color-light-gray);
  }
```
PostCSS will not warn when building this.  However if this is packaged up as a module, and imported by an upstream project, then postcss will warn that it cannot resolve the variable `--color-light-gray`;

### LINKED ISSUE #122: No access to the variable declared in another file
The plugin doesn't transform variable, declared in another file, to a value. In context of React. I used simple css loader and postcss-preset-env
# INPUT
*component1.css*
```css
:root {
   --color: red;
}
```

*component2.css*
```css
* {
   color: var(--color);
}
```

# OUTPUT
```css
* {
   color: var(--color);
   color: var(--color);
}
```

# EXPECTED OUTPUT
```css
 * {
   color: red;
   color: var(--color);
}
```

But if I declared and used a variable in one file it transformed as expected.
Or mb it's correct behavior and I don't understand something :(
Could someone explain?

### LINKED ISSUE #124: Can't overwrite options.variables locally
Given something like:

```
        'custom-properties': {
          appendVariables: true,
          warnings: true,
          variables: { brand: 'blue' },
        },
```

I cannot do this in a css file:
```
:root {
  --brand: 'red';
}

div {
  color: var(--brand);
}
```

The `div` will still effectively be `color: blue` because variables are appended, not prepended (and dont work unless appended?)

Is this expected behavior? Is there ways around this that I'm not understanding?

----

FWIW here's how I'm getting around this right now:

1. disable `custom-properties`
2. use [`postcss-css-variables`](https://github.com/MadLittleMods/postcss-css-variables) instead

### LINKED ISSUE #125: variable not set
Hi, I was using cssnext in my previous project but since the package is deprecated, I'm trying to update to postcss-preset-env with `postcss.config.js` file ton config postcss.

## Issue
When I add `custom-properties` to my features config, I have no error but the variable isn't recognized anymore even if I add variable in the config or load it from external file.

This is what I tried :

### postcss.config.js - test 1
```javascript
module.exports = {
  ident: 'postcss',
  plugins: () => [
    postcssPresetEnv({
      stage: 3,
    }),
    postCSSCustomProperties({
      appendVariables: true,
      variables: {
        hnfBlue: '#000',
        contrastBlue: '#000',
        textColor: '#000',
      },
    }),
  ],
};
```
### postcss.config.js - test 2 and 3

```javascript
module.exports = {
  ident: 'postcss',
  plugins: () => [
    postcssPresetEnv({
      stage: 3,
      features: {
        'custom-properties': {
           variables: require('./src/styles/variables.js') // or json
         }
      }
    }),
  ],
};
```
and here is my webpack config file :

```javascript
{
  test: /\.css$/,
    use: [
      'style-loader',
        { loader: 'css-loader', options: { importLoaders: 1 } },
        { loader: 'postcss-loader' }
    ]
},
```

my old conf with cssnext :
```js
module.exports = {
  ident: 'postcss',
  plugins: [
    require("postcss-easy-import")({ prefix: "_" }),
    require("postcss-url")({ url: "inline" }),
    require('postcss-flexbugs-fixes'),
    require('postcss-import'),
    require('postcss-cssnext')({
      features: {
        customProperties: {
          variables: {
            "stone": "#D8D8D8",
            "lightStone": "#4A4A4A",
            "cender": "#1E1A1B",
            "ice": "#FAFAFA",
          },
        },
        customMedia: {
          extensions: {
            '--phone': '(min-width: 544px)',
            '--tablet': '(min-width: 768px)',
            '--desktop': '(min-width: 992px)',
            '--large-desktop': '(min-width: 1200px)',
          },
        },
      },
    }),
  ],
};
```

Did Somebody have the same issue ?

### LINKED ISSUE #129: CSS Variable Dependence in Root
I was using postcss-custom-properties to produce fallback values for IE theming. Our application has hundreds of color variables, and we have them declared in root. I understand the transforming of the custom properties that contain var() in root, but should CSS variables that depend upon other CSS variables also be transformed and thus produce a duplicate variable declaration?

# Input
```css
:root {
    --color1: red;
    --color2: var(--color1);
    --color3: var(--color2);
    
    background-color: var(--color3);
}
```
# Expected
```css
:root {
    --color1: red;
    --color2: var(--color1);
    --color3: var(--color2);
    
    background-color: red;
    background-color: var(--color3);
}
```
# Actual
```css
:root {
    --color1: red;
    --color2: red;
    --color2: var(--color1);
    --color3: red;
    --color3: var(--color2);
    
    background: red;
    background-color: var(--color3);
}
```
Is this duplication necessary for obtaining the correct fallback values for css variables that depend upon another? If not, should there be an option to not transform css variable declarations?

### LINKED ISSUE #131: Allow to filter preserved custom properties
Due to runtime performance of root current properties on large applications, it would be nice to allow a mix of preserved and removed custom properties. The idea is to remove runtime properties which you want to be static to improve performance, whereas to leave at runtime those who are dynamic such as involved in the theme.

[Article about runtime performance of CSS variables](https://lisilinhart.info/posts/css-variables-performance).

### PR DESCRIPTION
**Pull request by jonathantneal**
### New features

- Added: New `exportTo` function to specify where to export custom properties to.
- Added: New `importFrom` option to specify where to import custom properties from.
- Added: Support for custom properties declared within `html` rules.
- Added: Support for PostCSS v7.
- Added: Support for Node v6+.
- Fixed: Custom Properties in `:root` are not also transformed.
- Fixed: Declarations that do not change are not duplicated when `preserve` is `true`.

### Removed features

- Removed: `strict` option, as using the fallback value isn’t necessarily more valid.
- Removed: `preserve: "computed"` option, as there seems to be little use in preserving custom property declarations while removing all usages of them.
- Removed: `warnings` and `noValueNotifications` options, as this should be the job of a linter tool.
- Removed: `variables` option, which is now replaced by `importFrom`
- Removed: `appendVariables` option, which is now replaced by `exportTo`

### Resolves

Resolves #80
Resolves #100
Resolves #102
Resolves #109
Resolves #113 
Resolves #122
Resolves #124
Resolves #125
Resolves #129
Resolves #131

---

With this update, all of the “custom” plugins (Custom Properties, Custom Selectors, and Custom Media) will be able to import and export variables to and from CSS, JS, and JSON files.

These features and some fixes resolve every open single issue in the repository. Namely, this update resolves the issue with Webpack users needing to reference variables from a single, master file.

This update also allows communication from PostCSS to client-side libraries that want to reference custom properties, selectors, or media in JS. This update also allows communication to PostCSS from design apps that can export master files of custom properties, selectors, and media themselves.

### CODE REVIEW

**Comment by pascalduez** [comment]
> Removed: warnings and noValueNotifications options, as this should be the job of a linter tool.

Not sure a linter will be able to properly check all of this, especially for cases where the custom properties are defined in separate files, or imported from JS.

**Comment by pascalduez** [comment]
> this would be especially true for postcss-preset-env users, who might skip running this plugin altogether based upon their browserslist.

Good point! :)

**Comment by gpoitch** [comment]
@jonathantneal @pascalduez adding my +1 to bring back the warnings option even though it probably should be a linter responsibility.  Looked into using stylelint led to a dead end: https://github.com/stylelint/stylelint/issues/2220

**Comment by pascalduez** [comment]
@gpoitch I'll give a try at creating a stylelint plugin, makes me quite curious.

**Comment by jonathantneal** [comment]
@gpoitch, @pascalduez, that poor issue was opened before its time. 😞

**Comment by jonathantneal** [comment]
If it helps, I spent some time tonight trying to learn how one writes a stylelint plugin. Maybe this is an okay template?

https://github.com/jonathantneal/value-no-unknown-custom-properties

**Comment by jonathantneal** [comment]
@pascalduez, @gpoitch. I’ve published the plugin.

https://github.com/csstools/stylelint-value-no-unknown-custom-properties

**Pull request merged**
