### PR TITLE
Throw error for circular variables references

### PR DESCRIPTION
**Pull request by hgl**
Fix the things I mentioned in the gist.

### CODE REVIEW

**Comment by MoOx** [comment]
No test, no merge. I need to see what are the improvements here.
This also need docs & a line in the CHANGELOG too please.

**Comment by hgl** [comment]
I was going to add unit tests. But what this does is to simply throw an error. And none of the unit tests test thrown error. So not sure how to test it.

For such code
```js
:root {
	--color: var(--bg-color);
	--bg-color: var(--color)
}
body {
	color: var(--bg-color);
}
```

It throws:
```
self-referential variable: --bg-color
```

Manually tested.

**Comment by hgl** [comment]
Once you think the commit is good, I will add doc and changelog.

**Comment by hgl** [comment]
This commit does two things:

- Throw error for self-referential variables
- Cache resolved variable for faster resolution

Both don't affect normal usage. Not sure if I should mention them in doc.

**Comment by hgl** [comment]
Fixed caching.

**Comment by MoOx** [comment]
Please add a test using https://github.com/substack/tape#tthrowsfn-expected-msg
Example here https://github.com/MoOx/reduce-css-calc/blob/master/test/index.js

**Comment by hgl** [comment]
Done.

**Comment by hgl** [comment]
Just found out this.

> If there is a cycle in the dependency graph, all the custom properties in the cycle must compute to their initial value (which is a guaranteed-invalid value)

> The initial value of a custom property is an empty value

Probably shouldn't throw an error?

**Comment by MoOx** [comment]
Just a warning. See postcss 4.1 api.

**Comment by hgl** [comment]
I end up using `console.warn` as you did for undefined variables.

**Pull request merged**
