### PR TITLE
Added: noValueNotifications option

### PR DESCRIPTION
**Pull request by SuperOl3g**
Few days ago I've written in #56 it would be great if we have the possibility to throw errors instead of warnings.
So I did it.

### CODE REVIEW

**Comment by SuperOl3g** [comment]
ping

**Comment by ai** [comment]
Ping @jonathantneal

**Comment by jonathantneal** [comment]
Pong @SuperOl3g

**Comment by SuperOl3g** [comment]
Thanks a lot!)

**Comment by SuperOl3g** [comment]
Hi there! How about release this feature and update npm package?)

**Comment by jonathantneal** [comment]
Happy to. I also just realized I don't know who the active maintainer of this plugin is.

**Comment by SuperOl3g** [comment]
ping @ai

**Comment by SuperOl3g** [comment]
ping @MoOx

**Comment by MoOx** [comment]
@jonathantneal have the proper right to publish this for a while :p

**Comment by jonathantneal** [comment]
Doh. I’ve had a wild couple months. I’m really sorry. I will review this.

**Comment by SuperOl3g** [comment]
Thanks, I will look forward)

**Comment by jonathantneal** [comment]
Published!

**Comment by SuperOl3g** [comment]
Yay! Great! 🎉

**Pull request merged**
